### PR TITLE
removed readline

### PR DESCRIPTION
**Pull request by ShreehariA**
It is said pyreadline3 can work on both Mac and Windows; I hope it does.

### CODE REVIEW

**Comment by tolitius** [comment]
mac and linux don't like this :(

seems like "pyreadline" needs '`windll`'

```
Traceback (most recent call last):
  File "/opt/venvs/foobar/lib/python3.11/site-packages/pyreadline3/keysyms/__init__.py", line 15, in <module>
    from .keysyms import *
  File "/opt/venvs/foobar/lib/python3.11/site-packages/pyreadline3/keysyms/keysyms.py", line 13, in <module>
    from ctypes import windll
ImportError: cannot import name 'windll' from 'ctypes' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py)
```

**Comment by ShreehariA** [comment]
I just built it and tried it with the new version, and it works:

Screenshot 2024-04-11 230546

**Comment by tolitius** [comment]
the PR did not work as is (at least on mac & linux)
I [added](https://github.com/tolitius/jemma/commit/18a63daacf3b7226f3358239bf7a3727f342b392) windows support, it should be in the [latest jemma](https://pypi.org/project/jemma)

let me know if it works on your windows laptop

**Comment by tolitius** [comment]
@ShreehariA this can be closed if it works on windows
can you confirm?

**Comment by ShreehariA** [comment]
It works fine in windows. Closing the PR, Thanks for the support.

**Pull request closed without merging**
